"use client";

import { useActionState } from "react";
import { updateSettingsAction } from "./actions";
import { OpenAiKeyField } from "./openai-key-field";
import type { AppSettings } from "@/lib/settings";
import { RESUME_MODELS } from "@/lib/tailoring/models";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Alert } from "@/components/ui/alert";

export function SettingsForm({ settings }: { settings: AppSettings }) {
  const [state, formAction, pending] = useActionState(updateSettingsAction, undefined);

  return (
    <form action={formAction} className="flex flex-col gap-6">
      <Card>
        <CardHeader>
          <CardTitle>Resume generation</CardTitle>
          <CardDescription>
            Tailored resumes are generated by DeepSeek using the platform&apos;s managed resume prompt.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-5">
          <FormField label="DeepSeek model" htmlFor="resumeModel">
            <Select id="resumeModel" name="resumeModel" defaultValue={settings.resumeModel} className="max-w-xs">
              {RESUME_MODELS.map((m) => (
                <option key={m.id} value={m.id}>
                  {m.label} — {m.hint}
                </option>
              ))}
            </Select>
          </FormField>

          <FormField label="Resume PDF template" htmlFor="resumeTemplate">
            <Select id="resumeTemplate" name="resumeTemplate" defaultValue={settings.resumeTemplate} className="max-w-xs">
              <option value="MODERN">Modern</option>
              <option value="CLASSIC">Classic</option>
            </Select>
          </FormField>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>OpenAI</CardTitle>
          <CardDescription>
            Used for role-track classification, job-posting extraction (Chrome extension), and Application Checks.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-5">
          <OpenAiKeyField hasCustomKey={settings.hasCustomApiKey} apiKeyHint={settings.apiKeyHint} />

          <FormField
            label="OpenAI model"
            htmlFor="openaiModel"
            hint="Any valid OpenAI model name, e.g. gpt-4.1-mini, gpt-4.1."
          >
            <Input
              id="openaiModel"
              name="openaiModel"
              required
              defaultValue={settings.openaiModel}
              className="max-w-xs"
            />
          </FormField>
        </CardContent>
      </Card>

      {state?.error && <Alert variant="destructive">{state.error}</Alert>}
      {state?.success && <Alert variant="success">Settings saved.</Alert>}

      <Button type="submit" loading={pending} className="self-start">
        {pending ? "Saving…" : "Save settings"}
      </Button>
    </form>
  );
}
